services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:admin@mongodb:27017
      REDIS_KEY: redis://redis:6379
      LOCALPORT: 5000

  redis: 
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    mem_limit: 1024m
    cpus: 2
    ports:
      - "6379:6379"
    command: >
      redis-server
      -- maxmemory 100mb
      -- maxmemory-policy allkeys-lru

  redis-exporter:
    image: oliver006/redis_exporter:alpine
    container_name: redis-exporter
    restart: unless-stopped
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "redis:6379"

  mongodb: 
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    mem_limit: 1024m
    cpus: 2

  mongo-exporter:
    image: percona/mongodb_exporter:0.44.0
    container_name: mongo-exporter
    restart: unless-stopped
    ports:
      - "9216:9216"
    command:
      - "--mongodb.uri=mongodb://admin:admin@mongodb:27017/admin"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  mongodata:
  grafana-storage:
